general:
  startup_commands: ['shell-exec zebar']
  shutdown_commands: ['shell-exec taskkill /IM zebar.exe /F']
  config_reload_commands: []
  focus_follows_cursor: false
  toggle_workspace_on_refocus: false
  cursor_jump:
    enabled: false
    trigger: 'monitor_focus'
  hide_method: 'cloak'
  show_all_in_taskbar: false

gaps:
  scale_with_dpi: true
  outer_gap:
    top: '40px'
    right: '0px'
    bottom: '0px'
    left: '0px'

window_effects:
  focused_window:
    border:
      enabled: true
      color: '#0000ff'
    hide_title_bar:
      enabled: true
    corner_style:
      enabled: true
      style: 'rounded'
  other_windows:
    border:
      enabled: true
      color: '#a1a1a1'
    hide_title_bar:
      enabled: true
    corner_style:
      enabled: true
      style: 'rounded'

window_behavior:
  initial_state: 'tiling'
  state_defaults:
    floating:
      centered: true
      shown_on_top: true
    fullscreen:
      maximized: true
      shown_on_top: true

workspaces:
  - name: '1'
  - name: '2'
  - name: '3'
  - name: '4'
  - name: '5'
  - name: '6'
  - name: '7'
  - name: '8'
  - name: '9'

window_rules:
  - commands: ['ignore']
    match:
      - window_process: { equals: 'zebar' }
      - window_title: { regex: '[Pp]icture.in.[Pp]icture' }
        window_class: { regex: 'Chrome_WidgetWin_1|MozillaDialogClass' }
      - window_process: { equals: 'PowerToys' }
        window_class: { regex: 'HwndWrapper\[PowerToys\.PowerAccent.*?\]' }
      - window_process: { equals: 'PowerToys' }
        window_title: { regex: '.*? - Peek' }
      - window_process: { equals: 'Lively' }
        window_class: { regex: 'HwndWrapper' }

      - window_title: { regex: 'Herinneringen' }
      - window_process: { equals: 'SnippingTool' }
  # - commands: ['move --workspace 1']
  #   match:
  #     - window_process: { equals: 'msedge' }
  - commands: ['move --workspace 7']
    match:
      - window_process: { equals: 'ms-teams' }
  - commands: ['move --workspace 8']
    match:
      - window_process: { regex: 'olk' } # outlook

binding_modes:
  - name: 'resize'
    keybindings:
      - commands: ['resize --width -2%']
        bindings: ['h', 'left']
      - commands: ['resize --width +2%']
        bindings: ['l', 'right']
      - commands: ['resize --height +2%']
        bindings: ['k', 'up']
      - commands: ['resize --height -2%']
        bindings: ['j', 'down']
      - commands: ['wm-disable-binding-mode --name resize']
        bindings: ['escape', 'enter', 'alt+r']

keybindings:
  - commands: ['focus --direction left']
    bindings: ['alt+h', 'alt+left']
  - commands: ['focus --direction right']
    bindings: ['alt+l', 'alt+right']
  - commands: ['focus --direction up']
    bindings: ['alt+k', 'alt+up']
  - commands: ['focus --direction down']
    bindings: ['alt+j', 'alt+down']

  # Move focused window in a given direction.
  - commands: ['move --direction left']
    bindings: ['alt+shift+h', 'alt+shift+left']
  - commands: ['move --direction right']
    bindings: ['alt+shift+l', 'alt+shift+right']
  - commands: ['move --direction up']
    bindings: ['alt+shift+k', 'alt+shift+up']
  - commands: ['move --direction down']
    bindings: ['alt+shift+j', 'alt+shift+down']

  # Resize focused window by a percentage or pixel amount.
  - commands: ['resize --width -2%']
    bindings: ['alt+u']
  - commands: ['resize --width +2%']
    bindings: ['alt+p']
  - commands: ['resize --height +2%']
    bindings: ['alt+o']
  - commands: ['resize --height -2%']
    bindings: ['alt+i']

  # Resize mode.
  - commands: ['wm-enable-binding-mode --name resize']
    bindings: ['alt+r']
  # Change tiling direction.
  - commands: ['toggle-tiling-direction']
    bindings: ['alt+v']

  # Change the focused window to be tiling.
  - commands: ['toggle-floating --centered']
    bindings: ['lwin+t']

  # Change the focused window to be fullscreen.
  - commands: ['toggle-fullscreen']
    bindings: ['lwin+f']

  # Minimize focused window.
  - commands: ['toggle-minimized']
    bindings: ['alt+m']

  # Close focused window.
  - commands: ['close']
    bindings: ['lwin+q']

  # Kill GlazeWM process safely.
  - commands: ['wm-exit']
    bindings: ['alt+shift+e']

  # Re-evaluate configuration file.
  - commands: ['wm-reload-config']
    bindings: ['alt+shift+r']

  # Redraw all windows.
  - commands: ['wm-redraw']
    bindings: ['alt+shift+w']

  # Change focus to a workspace defined in `workspaces` config.
  - commands: ['focus --workspace 1']
    bindings: ['alt+1']
  - commands: ['focus --workspace 2']
    bindings: ['alt+2']
  - commands: ['focus --workspace 3']
    bindings: ['alt+3']
  - commands: ['focus --workspace 4']
    bindings: ['alt+4']
  - commands: ['focus --workspace 5']
    bindings: ['alt+5']
  - commands: ['focus --workspace 6']
    bindings: ['alt+6']
  - commands: ['focus --workspace 7']
    bindings: ['alt+7']
  - commands: ['focus --workspace 8']
    bindings: ['alt+8']
  - commands: ['focus --workspace 9']
    bindings: ['alt+9']

  # Move the focused window
  - commands: ['move-workspace --direction left']
    bindings: ['alt+a']
  - commands: ['move-workspace --direction right']
    bindings: ['alt+f']
  - commands: ['move-workspace --direction up']
    bindings: ['alt+d']
  - commands: ['move-workspace --direction down']
    bindings: ['alt+s']

  # Move focused window to a workspace
  - commands: ['move --workspace 1']
    bindings: ['alt+shift+1']
  - commands: ['move --workspace 2']
    bindings: ['alt+shift+2']
  - commands: ['move --workspace 3']
    bindings: ['alt+shift+3']
  - commands: ['move --workspace 4']
    bindings: ['alt+shift+4']
  - commands: ['move --workspace 5']
    bindings: ['alt+shift+5']
  - commands: ['move --workspace 6']
    bindings: ['alt+shift+6']
  - commands: ['move --workspace 7']
    bindings: ['alt+shift+7']
  - commands: ['move --workspace 8']
    bindings: ['alt+shift+8']
  - commands: ['move --workspace 9']
    bindings: ['alt+shift+9'] 

  # Launch terminal(git-bash)
  - commands: ['shell-exec wt']
    bindings: ['alt+enter', 'lwin+enter']

  # Launch browser(ms edge)
  - commands: ['shell-exec msedge.exe']
    bindings: ['lwin+b']

  # Launch select-area to crop screenshot
  - commands: ['shell-exec SnippingTool.exe']
    bindings: ['lwin+o']
