# ALIASES

alias v="nvim"
alias 'v.'="nvim ."

alias q="exit"
alias ':q'="exit"

alias l="ls -lah"

alias '..'="cd .."
alias '...'="cd ../.."
alias '....'="cd ../../.."

# VARS


# APPS

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
